### PR TITLE
Add option to lowercase default entity collection name

### PR DESCRIPTION
**Pull request by RainoBoy97**
Option to lowercase the default entity collection name when nothing is specified in the @Entity annotation!

### CODE REVIEW

**Comment by ParaPenguin** [comment]
Would also be nice if capital letters in the class name were prepended with an underscore.

**Comment by evanchooly** [comment]
This is great.  But it'd be event better with tests.  :)

**Comment by RainoBoy97** [comment]
Added a test. I used the already existing `MapperOptionsTest` class because it seemed like an appropriate place to put it.

The commit messages got messed up on my fork, but thankfully it didnt mess up the pull request :)

**Comment by RainoBoy97** [comment]
Since you added it manually and not merging I guess this can be closed.

**Comment by evanchooly** [comment]
It is closed.

**Comment by RainoBoy97** [comment]
Oh wow, how did I not notice that...

**Pull request closed without merging**
