### PR TITLE
prevent always warning on versioned updates for non-objectid keys

### PR DESCRIPTION
**Pull request by scottbessler**

### CODE REVIEW

**Comment by evanchooly** [comment]
Two questions:

1.  Is this the only place this is an issue?  
1.  Is there a unit test that shows this logging noise?  It shouldn't be complaining about non-ObjectId's in the first place so this is probably part of a larger validation bug.

**Comment by scottbessler** [comment]
This particular location is sending a basicdbobject as part of the query it
seems.

As for testing, do you have existing examples of tests for logging noise I
could learn from?

-scott
eng@relateiq

On May 13, 2015 at 5:22 AM Justin Lee <notifications@github.com> wrote:

  Two questions:

   1. Is this the only place this is an issue?
    2. Is there a unit test that shows this logging noise? It shouldn't be
   complaining about non-ObjectId's in the first place so this is probably
   part of a larger validation bug.

—
Reply to this email directly or view it on GitHub
<https://github.com/mongodb/morphia/pull/771#issuecomment-101646445>.

**Comment by evanchooly** [comment]
Oh, so you're mixing in driver class in to your query?  hrm.  well that's probably why you're seeing the validation messages.  Any reason you're not using a Key?

**Comment by scottbessler** [comment]
No actually it's a use of @versioned saving of a doc with an id that is a
Java object. I can add a repro case when I get in to work.
-scott
eng@relateiq

On May 13, 2015 at 6:12 AM Justin Lee <notifications@github.com> wrote:

  Oh, so you're mixing in driver class in to your query? hrm. well that's
probably why you're seeing the validation messages. Any reason you're not
using a Key?

—
Reply to this email directly or view it on GitHub
<https://github.com/mongodb/morphia/pull/771#issuecomment-101658574>.

**Comment by scottbessler** [comment]
Key class, using lombok to simplify:
```java
@Data
@NoArgsConstructor
@RequiredArgsConstructor
public class ConfigKey {
    @NonNull
    private String env;

    @NonNull
    private String subenv;

    @NonNull
    private String key;

}
```

Object class:
```java
@Data
@NoArgsConstructor
@RequiredArgsConstructor
@Entity(noClassnameStored = true)
public class ConfigEntry {

    @Id @NonNull
    private ConfigKey key;

    @NonNull
    private String value;

    @Version
    private long version;

    @NonNull
    private String lastModifiedUser;

    @NonNull
    private long lastModifiedMillis;

}
```

Code that generates a warning:
```
BasicDAO<ConfigEntry, ConfigKey> innerDAO = new BasicDAO<>(ConfigEntry.class, ds);
ConfigEntry entry = fetchEntry();
entry.setValue(value);
innerDAO.save(entry);
```

The warning:
```
2015-05-13 15:58:43,486  WARN org.mongodb.morphia.query.QueryValidator: 108 - Validation warnings: 
[Validation failed: 'Type com.relateiq.qonf.server.entity.ConfigKey may not be queryable with value '{ "env" : "*" , "subenv" : "*" , "key" : "test"}' with class com.mongodb.BasicDBObject']
```

**Comment by evanchooly** [comment]
Merged to the 1.0.x branch
will cherry pick to master

**Pull request closed without merging**
