### PR TITLE
Allow Proper Implementation of Accumulator Sum

### PR DESCRIPTION
**Pull request by AddoSolutions**
See Issue #632

### CODE REVIEW

**Comment by evanchooly** [comment]
Given that `field` is a name, i'm not sure what changing this to `Object` really accomplishes.  Given the time lapsed since a test was requested with no response, I'll probably end up just closing this one unless I hear something soon.

**Comment by AddoSolutions** [comment]
You cannot give an integer for `$sum`, for example, to tell morphia to sum the values.

exmaple:

```
		AggregationPipeline<Stat, AggregateTarget> pipeline
			= getDs().<Stat, AggregateTarget>createAggregation(Stat.class)
			.match(query)
			.group("target", grouping("total", new Accumulator("$sum", 1)))
			.sort(new Sort("total", -1))
			.limit(limit);
```

Notice on the third line: `new Accumulator("$sum", 1)` – if that is a String, it is parsed as `{ $sum : "1" }` when in order for Mongo to do the indexing, it must be: `{ $sum : 1 }` as an integer or in some cases a BasicDBObject.

See: http://docs.mongodb.org/manual/reference/operator/aggregation/sum/

**Comment by evanchooly** [comment]
oh!  right.  I see.  That makes way more sense now.  Thanks.

**Comment by evanchooly** [comment]
@AddoSolutions can you add a unit test or two to the pull request? I can merge it for 0.111.

**Comment by AddoSolutions** [comment]
Not to n00b you out, but could you give me an example of what you are looking for?  Thanks :)

**Comment by evanchooly** [comment]
e.g., when I added the new text indexing bits, i added this test:  https://github.com/mongodb/morphia/blob/master/morphia/src/test/java/org/mongodb/morphia/indexes/TestTextIndexing.java

Something that shows it in use for the users and something that shows it works for the devs.

**Pull request closed without merging**
