### PR TITLE
fix testOut in AggregationTest

### PR DESCRIPTION
**Pull request by mich8bsp**
The order should be Dante first and then Homer. Also, checking book list for both authors

### CODE REVIEW

**Comment by evanchooly** [comment]
This test is currently already passing locally, and jenkins and travis.  are you seeing a failure here?

**Comment by mich8bsp** [comment]
I did see a failure, for MongoDB 3.2.1. Since you said the test is passing, I went back and ran it against 3.0.9 and it passed. I guess something in the order of the cursor iterator changed between the versions. I guess I shouldn't use 3.2.1 with morphia relying on java driver 3.0.2

**Comment by evanchooly** [comment]
I'm running tests against 3.2.1 just fine.  That's odd.  What OS?

**Comment by mich8bsp** [comment]
Win10 64-bit... Weird that we're getting different results, I'll try to look into it...

**Comment by a-h** [comment]
I got the same failing test and fixed it in pretty much the same way, except that I added an order to the aggregation to make sure that Dante always comes out before Homer.

**Comment by evanchooly** [comment]
The plan is for 1.4 to make significant updates to aggregation.  I'm going to close this for now with the understanding that the underlying issue will be properly cleaned up with the finished aggregation API.

**Pull request closed without merging**
